// EPQ · CONCURSO RADAR — Fonte de dados estruturada
// Estrutura: concursos, histórico, alertas, fontes, parâmetros de scoring

export const RADAR_VERSION = '0.1.0';
export const LAST_UPDATED = '2026-09-04';

export const SCOPE_FOCUS = [
  'PMERJ','Polícia Civil','Polícia Penal','Polícia Federal','PRF',
  'Bombeiros','Guardas Municipais','área militar','área administrativa',
  'tribunais','educação','saúde','segurança pública'
];

export const STATUS_FLOW = [
  'MOVIMENTAÇÃO','AUTORIZADO','BANCA','EDITAL','INSCRIÇÕES','PROVA','ENCERRADO'
];

export const SCORE_BANDS = [
  { min: 80, max: 100, label: '🔥 PRIORIDADE MÁXIMA', color: '#ff3b3b' },
  { min: 60, max: 79,  label: '🟢 OPORTUNIDADE', color: '#22c55e' },
  { min: 40, max: 59,  label: '🟡 MONITORAR', color: '#facc15' },
  { min: 0,  max: 39,  label: '⚪ BAIXA PRIORIDADE', color: '#94a3b8' }
];

export const DECISIONS = [
  { id:'ABRIR', label:'ABRIR AGORA', color:'#ef4444' },
  { id:'PRE',  label:'PRÉ-LANÇAR',  color:'#f97316' },
  { id:'CAPTAR',label:'CAPTAR LEADS',color:'#3b82f6' },
  { id:'MONITORAR',label:'MONITORAR',color:'#facc15' },
  { id:'NAO_ATACAR',label:'NÃO ATACAR',color:'#94a3b8' }
];

export const RELIABILITY = [
  { id:'CONFIRMADO', label:'Confirmado', weight: 100 },
  { id:'INDICIO',    label:'Indício', weight: 75 },
  { id:'PREVISAO',   label:'Previsão', weight: 50 },
  { id:'RUMOR',      label:'Rumor', weight: 25 }
];

export const sources = [
  { id:'oficial', name:'Órgão oficial / Diário Oficial', reliabilityWeight: 100 },
  { id:'banca',   name:'Banca organizadora', reliabilityWeight: 90 },
  { id:'especializada', name:'Portal especializado', reliabilityWeight: 70 },
  { id:'comunidade', name:'Comunidade/canal', reliabilityWeight: 55 }
];

export const concursos = [
  {
    id:'PMERJ-2026',
    nome:'PMERJ',
    orgão:'Polícia Militar do Estado do Rio de Janeiro',
    cargo:'Soldado / Oficial',
    estado:'RJ',
    area:'segurança pública',
    banca:'A definir',
    status:'IMINENTE',
    etapaAtual:'BANCA',
    ultimaMovimentacao:'Comissão formada e autorização em discussão',
    proximaEtapa:'EDITAL',
    previsaoEdital:'2026-10',
    previsaoProva:'2026-12',
    janelaComercialEstimada:'30–60 dias',
    vagasEstimadas:2000,
    remuneracaoEstimada:'R$ 3,7k–R$ 5,8k',
    escolaridade:'Nível médio / superior',
    publicoPotencial:'Alto',
    historicoDemanda:'Alta recorrência e fluxo contínuo de leads',
    aderenciaEPQ:95,
    potencialTicket:'Alto',
    concorrenciaCursos:'Alta',
    disciplinas:['Português','Matemática','Direito Constitucional','Direitos Humanos','Legislação PM'],
    existeMaterial:true,
    existeTurma:false,
    forcaMovimentacao:82,
    recenciaDias:7,
    score:92,
    tendencia:'subindo',
    aceleração:true,
    aceleraçãoRazao:'2 movimentações em 14 dias'
  },
  {
    id:'PRF-2026',
    nome:'PRF',
    orgão:'Polícia Rodoviária Federal',
    cargo:'Agente / Policial',
    estado:'DF',
    area:'segurança pública',
    banca:'A definir',
    status:'EM ESTUDO',
    etapaAtual:'MOVIMENTAÇÃO',
    ultimaMovimentacao:'Pedido de autorização em análise',
    proximaEtapa:'AUTORIZADO',
    previsaoEdital:'2026-12',
    previsaoProva:'2027-02',
    vagasEstimadas:1500,
    remuneracaoEstimada:'R$ 9,8k+',
    escolaridade:'Nível superior',
    publicoPotencial:'Alto',
    historicoDemanda:'Alta',
    aderenciaEPQ:90,
    potencialTicket:'Alto',
    concorrenciaCursos:'Alta',
    disciplinas:['Português','Matemática','Direito Constitucional','Direito Administrativo','Legislação PRF'],
    existeMaterial:true,
    existeTurma:false,
    forcaMovimentacao:58,
    recenciaDias:18,
    score:78,
    tendencia:'estável',
    aceleração:false,
    aceleraçãoRazao:'Sem novidades recentes'
  },
  {
    id:'PC-RJ-AGENTE-2026',
    nome:'Polícia Civil RJ',
    orgão:'Polícia Civil do Estado do Rio de Janeiro',
    cargo:'Agente / Escrivão / Inspetor',
    estado:'RJ',
    area:'segurança pública',
    banca:'A definir',
    status:'IMINENTE',
    etapaAtual:'BANCA',
    ultimaMovimentacao:'Autorização publicada e comissão nomeada',
    proximaEtapa:'EDITAL',
    previsaoEdital:'2026-10',
    previsaoProva:'2026-12',
    vagasEstimadas:900,
    remuneracaoEstimada:'R$ 5,2k–R$ 7,4k',
    escolaridade:'Nível superior',
    publicoPotencial:'Alto',
    historicoDemanda:'Alta no Rio',
    aderenciaEPQ:92,
    potencialTicket:'Alto',
    concorrenciaCursos:'Alta',
    disciplinas:['Português','Direito Constitucional','Direito Penal','Processo Penal','Legislação PC'],
    existeMaterial:true,
    existeTurma:false,
    forcaMovimentacao:74,
    recenciaDias:12,
    score:85,
    tendencia:'subindo',
    aceleração:true,
    aceleraçãoRazao:'Publicação oficial recente'
  },
  {
    id:'TRF2-ANALISTA-2026',
    nome:'TRF2',
    orgão:'Tribunal Regional Federal da 2ª Região',
    cargo:'Analista Judiciário',
    estado:'RJ/ES',
    area:'tribunais',
    banca:'FGV / A definir',
    status:'EM ESTUDO',
    etapaAtual:'MOVIMENTAÇÃO',
    ultimaMovimentacao:'Movimentação interna de estrutura',
    proximaEtapa:'AUTORIZADO',
    previsaoEdital:'2027-01',
    previsaoProva:'2027-03',
    vagasEstimadas:300,
    remuneracaoEstimada:'R$ 7k–R$ 13k',
    escolaridade:'Nível superior',
    publicoPotencial:'Médio-alto',
    historicoDemanda:'Recorrente',
    aderenciaEPQ:78,
    potencialTicket:'Alto',
    concorrenciaCursos:'Média-alta',
    disciplinas:['Português','Direito Constitucional','Direito Administrativo','Informática'],
    existeMaterial:true,
    existeTurma:false,
    forcaMovimentacao:45,
    recenciaDias:35,
    score:64,
    tendencia:'estável',
    aceleração:false,
    aceleraçãoRazao:'Sem aceleração detectada'
  },
  {
    id:'GUARDA-CIVIL-MG-2026',
    nome:'Guarda Civil MG',
    orgão:'Prefeitura de BH / Governo MG',
    cargo:'Guarda Municipal',
    estado:'MG',
    area:'segurança pública',
    banca:'A definir',
    status:'EM ESTUDO',
    etapaAtual:'MOVIMENTAÇÃO',
    ultimaMovimentacao:'Estudo de viabilidade',
    proximaEtapa:'AUTORIZADO',
    previsaoEdital:'2027-01',
    previsaoProva:'2027-03',
    vagasEstimadas:500,
    remuneracaoEstimada:'R$ 3k–R$ 5k',
    escolaridade:'Nível médio',
    publicoPotencial:'Médio',
    historicoDemanda:'Média',
    aderenciaEPQ:68,
    potencialTicket:'Médio',
    concorrenciaCursos:'Média',
    disciplinas:['Português','Matemática','Direito Constitucional','Legislação GM'],
    existeMaterial:false,
    existeTurma:false,
    forcaMovimentacao:38,
    recenciaDias:55,
    score:52,
    tendencia:'estável',
    aceleração:false,
    aceleraçãoRazao:'Sem sinais fortes'
  },
  {
    id:'BOMBEIROS-RJ-2026',
    nome:'CBMERJ',
    orgão:'Corpo de Bombeiros do Estado do Rio de Janeiro',
    cargo:'Soldado / Oficial',
    estado:'RJ',
    area:'segurança pública',
    banca:'A definir',
    status:'IMINENTE',
    etapaAtual:'AUTORIZADO',
    ultimaMovimentacao:'Autorização confirmada pelo estado',
    proximaEtapa:'BANCA',
    previsaoEdital:'2026-11',
    previsaoProva:'2027-01',
    vagasEstimadas:1200,
    remuneracaoEstimada:'R$ 3,5k–R$ 6k',
    escolaridade:'Nível médio / superior',
    publicoPotencial:'Alto',
    historicoDemanda:'Alta',
    aderenciaEPQ:88,
    potencialTicket:'Alto',
    concorrenciaCursos:'Alta',
    disciplinas:['Português','Matemática','Física','Química','Legislação CBM'],
    existeMaterial:true,
    existeTurma:false,
    forcaMovimentacao:70,
    recenciaDias:20,
    score:80,
    tendencia:'subindo',
    aceleração:true,
    aceleraçãoRazao:'Avanço de etapa em menos de 30 dias'
  },
  {
    id:'EDUCACAO-SP-PROF-2026',
    nome:'Educação SP',
    orgão:'SEE/SP / Prefeituras',
    cargo:'Professor / Educação básica',
    estado:'SP',
    area:'educação',
    banca:'VUNESP / FCC / A definir',
    status:'EM ESTUDO',
    etapaAtual:'MOVIMENTAÇÃO',
    ultimaMovimentacao:'Discussão de calendário estadual',
    proximaEtapa:'AUTORIZADO',
    previsaoEdital:'2027-01',
    previsaoProva:'2027-03',
    vagasEstimadas:2000,
    remuneracaoEstimada:'R$ 2,8k–R$ 5,5k',
    escolaridade:'Nível superior',
    publicoPotencial:'Muito alto',
    historicoDemanda:'Muito alta e contínua',
    aderenciaEPQ:72,
    potencialTicket:'Médio-alto',
    concorrenciaCursos:'Alta',
    disciplinas:['Português','Didática','Conhecimentos Pedagógicos','Legislação Educacional'],
    existeMaterial:true,
    existeTurma:false,
    forcaMovimentacao:35,
    recenciaDias:45,
    score:61,
    tendencia:'estável',
    aceleração:false,
    aceleraçãoRazao:'Sem aceleração'
  },
  {
    id:'SAUDE-ENFERMAGEM-RJ-2026',
    nome:'Saúde RJ',
    orgão:'Prefeitura do Rio / SES-RJ',
    cargo:'Enfermeiro / Técnico',
    estado:'RJ',
    area:'saúde',
    banca:'A definir',
    status:'EM ESTUDO',
    etapaAtual:'MOVIMENTAÇÃO',
    ultimaMovimentacao:'Plano de contratações em discussão',
    proximaEtapa:'AUTORIZADO',
    previsaoEdital:'2027-02',
    previsaoProva:'2027-04',
    vagasEstimadas:800,
    remuneracaoEstimada:'R$ 3k–R$ 7k',
    escolaridade:'Técnico / superior',
    publicoPotencial:'Alto',
    historicoDemanda:'Alta',
    aderenciaEPQ:65,
    potencialTicket:'Médio',
    concorrenciaCursos:'Média',
    disciplinas:['Português','Direito Sanitário','Legislação de Saúde','Noções de Enfermagem'],
    existeMaterial:false,
    existeTurma:false,
    forcaMovimentacao:30,
    recenciaDias:60,
    score:54,
    tendencia:'estável',
    aceleração:false,
    aceleraçãoRazao:'Sem aceleração'
  }
];

export const historico = [
  { id:'PMERJ-2026', data:'2026-08-28', evento:'Comissão formada', fonte:'oficial', confianca:'Confirmado' },
  { id:'PMERJ-2026', data:'2026-09-04', evento:'Autorização em discussão', fonte:'especializada', confianca:'Indício' },
  { id:'PC-RJ-AGENTE-2026', data:'2026-08-25', evento:'Comissão nomeada', fonte:'oficial', confianca:'Confirmado' },
  { id:'PC-RJ-AGENTE-2026', data:'2026-09-02', evento:'Publicação oficial de autorização', fonte:'oficial', confianca:'Confirmado' },
  { id:'BOMBEIROS-RJ-2026', data:'2026-08-20', evento:'Movimentação inicial', fonte:'especializada', confianca:'Indício' },
  { id:'BOMBEIROS-RJ-2026', data:'2026-09-01', evento:'Autorização confirmada', fonte:'oficial', confianca:'Confirmado' }
];

export const alertas = [
  { id:1, tipo:'🚀 CONCURSO ACELERANDO', concurso:'PMERJ', mensagem:'2 etapas em menos de 14 dias.', prioridade:'alta', data:'2026-09-04' },
  { id:2, tipo:'🔥 EDITAL PUBLICADO', concurso:'PC RJ', mensagem:'Autorização publicada oficialmente.', prioridade:'alta', data:'2026-09-02' },
  { id:3, tipo:'🎯 OPORTUNIDADE DE NOVA TURMA', concurso:'PMERJ', mensagem:'Score 92 + aceleração = janela ideal para pré-lançamento.', prioridade:'alta', data:'2026-09-04' },
  { id:4, tipo:'🟠 BANCA DEFINIDA', concurso:'CBMERJ', mensagem:'Autorização confirmada; banca próxima.', prioridade:'média', data:'2026-09-01' }
];

export const scoringWeights = {
  proximidadeEdital: 18,
  inscricoesAbertas: 20,
  vagas: 10,
  relevanciaCargo: 12,
  historicoDemanda: 10,
  aderenciaEPQ: 12,
  concorrencia: 6,
  ticketPotencial: 6,
  recorrencia: 5,
  publico: 5,
  facilidadeTurma: 6,
  materialQuestoes: 5,
  disciplinasExistentes: 6,
  forcaMovimentacao: 9
};

export const automationConfig = {
  intervalHours: 24,
  fontes: ['oficial','banca','especializada'],
  notificarTipos: ['🔥 EDITAL PUBLICADO','🚀 CONCURSO ACELERANDO','⏰ INSCRIÇÕES ABERTAS']
};
